- name: install packages
  tags: packages
  package: name={{ item }} state=latest
  with_items:
    - neutron-server
    - neutron-linuxbridge-agent

- name: install configurations
  template: src={{ item }}.j2 dest=/etc/neutron/{{ item }}
  with_items:
    - neutron.conf
- template: src=linuxbridge_agent.ini.j2 dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini

- name: start services
  tags: service
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - nova-compute
    - neutron-linuxbridge-agent
